#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
IMAGE_NAME=${IMAGE_NAME:-ghcr.io/pasturestack/container-cron}
REVISION=${REVISION:-$(git rev-parse HEAD)}

cp ../bin/container-cron .
cp ../LICENSE .
cp ../SECURITY.md .
cp ../UNOFFICIAL_MAINTENANCE_FORK.md .
cp ../ORIGIN.md .
cp ../COMPATIBILITY.md .

docker_build_network_arg=()
if [ -n "${DOCKER_BUILD_NETWORK:-}" ]; then
    docker_build_network_arg=(--network="${DOCKER_BUILD_NETWORK}")
fi
DOCKER_BUILDKIT="${DOCKER_BUILDKIT:-0}" docker build "${docker_build_network_arg[@]}" \
    --build-arg UBUNTU_MIRROR="${UBUNTU_MIRROR:-http://archive.ubuntu.com/ubuntu}" \
    --build-arg VERSION="${TAG}" \
    --build-arg REVISION="${REVISION}" \
    -t "${IMAGE_NAME}:${TAG}" .

mkdir -p ../dist
echo "${IMAGE_NAME}:${TAG}" > ../dist/images
echo "Built ${IMAGE_NAME}:${TAG}"
