#!/bin/bash

if [ -n "${VERSION_OVERRIDE:-}" ]; then
    VERSION="${VERSION_OVERRIDE}"
elif [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

if [ -z "${VERSION:-}" ]; then
    COMMIT=$(git rev-parse --short HEAD)
    GIT_TAG=$(git tag -l --contains HEAD | head -n 1)

    if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
        VERSION=$GIT_TAG
    else
        VERSION="${COMMIT}${DIRTY}"
    fi
fi

if [ -z "${ARCH:-}" ]; then
    ARCH=amd64
fi
